<a href="https://colab.research.google.com/github/surendarmanoj/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Refer this sheet for Numpy Course Reference -> [Numpy By Agalya](https://docs.google.com/spreadsheets/d/1BVWAp4KR11xsxEmHqWUvBil8Sikq7TVnh3ZL7ajq5AU/edit?usp=sharing)

Numpy Random value -> [random value](https://docs.google.com/spreadsheets/d/1tnDWVhWgUC9BAU3iuZUIn_-r-ayOKsMp1GMqZUW9gBI/edit?usp=sharing)

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.shape

(3,)

In [ ]:
b = np.array([[[19,8,7,6,5,4],[1,2,3,4,5,0]]])
b

array([[[19,  8,  7,  6,  5,  4],
        [ 1,  2,  3,  4,  5,  0]]])

In [ ]:
b.shape

(1, 2, 6)

In [ ]:
b.ndim

3

In [ ]:
b.itemsize

8

In [ ]:
b = np.array([[19,8,7,6,5,4],[1,2,3,4,5,0]])
b.shape

(2, 6)

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
c[:,:1] = [[[9,9]],[[9,9]]]

In [ ]:
c

array([[[9, 9],
        [3, 4]],

       [[9, 9],
        [7, 8]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [ ]:
np.full_like(c, 10)

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [ ]:
np.random.randint(5,10,size=(3,5))

array([[5, 8, 6, 7, 7],
       [7, 7, 5, 7, 7],
       [9, 6, 8, 9, 8]])

In [ ]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
d = np.array([[1,2,3]])
e = np.repeat(d,3, axis=0)
e

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
f = np.full((5,5),9)
f

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
g = np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
f[1:4,1:4] = g

In [ ]:
f

array([[9, 9, 9, 9, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
f.shape

(5, 5)

In [ ]:
f[2][2]=8
f

array([[9, 9, 9, 9, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 8, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 10
a
b

array([ 1, 10,  3])

In [ ]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [ ]:
a-3

array([-2, -1,  0])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
a/2

array([0.5, 1. , 1.5])

In [ ]:
a = np.array([1,2,3,8])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 15])

In [ ]:
a ** 2

array([ 1,  4,  9, 64])

In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001, 0.98935825])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.14550003])

In [ ]:
a = np.ones((2,3))
b = np.full((3,2),2)
a
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(c)

1.0

In [ ]:
b = np.array([[[19,8,7,6,5,4],[1,2,3,4,5,0]]])
b

array([[[19,  8,  7,  6,  5,  4],
        [ 1,  2,  3,  4,  5,  0]]])

In [ ]:
np.min(b)

0

In [ ]:
np.max(b, axis=1)

array([[19,  8,  7,  6,  5,  4]])

In [ ]:
np.sum(b)

64

In [ ]:
b.shape

(1, 2, 6)

In [ ]:
c = b.reshape((1,6,2))
c

array([[[19,  8],
        [ 7,  6],
        [ 5,  4],
        [ 1,  2],
        [ 3,  4],
        [ 5,  0]]])

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1,v2, v1,v2])
v3


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
v3 = np.hstack([v1,v2, v1,v2])
v3

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np_a = np.genfromtxt('r_val.csv')
np_a


array([nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
np_a > 20

array([False, False, False, False, False, False, False, False, False])

In [ ]:
np_a1 = np.genfromtxt('r_val.csv', delimiter=',')
np_a2 = np_a1.astype('int32')
np_a2

array([[56,  6,  1, 31, 82, 15, 28],
       [10, 70, 24, 64, 25, 19, 18],
       [21, 96, 26, 96, 49,  5,  3],
       [92, 37, 22,  6, 30, 59, 11],
       [69, 79, 18, 57, 93, 75, 53],
       [ 5, 68, 34,  3, 62,  3, 42],
       [49, 50, 11, 31, 33, 35, 29],
       [99, 69, 33, 11, 10, 60, 81],
       [31, 82, 96, 55, 32, 45, 81]], dtype=int32)

In [ ]:
np_a2 > 20

array([[ True, False, False,  True,  True, False,  True],
       [False,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True, False],
       [ True,  True, False,  True,  True,  True,  True],
       [False,  True,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [ ]:
np_a2[np_a2 > 20]

array([56, 31, 82, 28, 70, 24, 64, 25, 21, 96, 26, 96, 49, 92, 37, 22, 30,
       59, 69, 79, 57, 93, 75, 53, 68, 34, 62, 42, 49, 50, 31, 33, 35, 29,
       99, 69, 33, 60, 81, 31, 82, 96, 55, 32, 45, 81], dtype=int32)